redengine/conditions/__init__.py, redengine/test/condition/test_parse.py
Following are now possible strategies:
``~has started today``
--> Runs once a day (alias to "daily")
``hourly & ~has failed today``
--> Hourly but if fails, won't run the rest of the day
Setting the task to default has been already tested
with these conditions thus works.
=> add: new parsing.

docs/condition_syntax/dependence.rst, docs/tutorial/pipeline_guide.rst, redengine/conditions/task/__init__.py, redengine/conditions/task/task.py, redengine/conditions/task/utils.py, redengine/parse/__init__.py, redengine/test/condition/test_parse.py
New syntax:
- ``after tasks 'task 1', 'task 2', 'task 3'``
- ``after any tasks 'task 1', 'task 2', 'task 3'``
- ``after any tasks 'task 1', 'task 2', 'task 3 succeeded'``
- ``after any tasks 'task 1', 'task 2', 'task 3' failed ``
- ``after any tasks 'task 1', 'task 2', 'task 3' finished``
- etc.
=> Compact after task

docs/code/demos/intermediate.py
- Updated the function name passed to `Return` in the code documentation from `do_on_process` -> `do_daily`.
- I've enjoyed testing out the library.  Thanks for releasing!
=> Rename Return function argument in documentation

rocketry/core/task.py, rocketry/test/app/test_app.py
Now this works:
```python
@app.task()
def do_never():
...
```
=> FIX: Minimal task

docs/versions.rst, rocketry/conditions/func.py, rocketry/test/app/test_cond_api.py
Making this possible:
```python
from rocketry.args import Task
@app.cond()
def is_foo(task=Task()):
...
```
=> fix: FuncCond parametrizing

docs/handbooks/index.rst, docs/handbooks/logging.rst, docs/index.rst, docs/tutorial/intermediate.rst, docs/versions.rst, rocketry/core/task.py, rocketry/test/task/func/test_logging.py
Previously the ``last_run``, ``last_success``, ``last_fail`` etc. were not fetched causing discontinuity if the scheduler was restarted (and logging repo is not ``MemoryRepo``).
Also updated docs a bit.
=> Fix: task status discontinuity in restart

rocketry/application.py, rocketry/core/schedule.py, rocketry/core/task.py, rocketry/session.py, rocketry/tasks/func.py, rocketry/test/app/test_app.py, rocketry/test/schedule/test_core.py, rocketry/test/schedule/test_methods.py, rocketry/test/schedule/test_terminate.py, rocketry/test/session/test_construct.py, rocketry/test/task/func/test_run.py, rocketry/test/task/test_core.py
This PR adds async support (#28) for the main scheduler but also adds support for parallelizing tasks as async.
For example:
```python
@app.task(execution="async")
async def 
```
Some notes:
- If ``async def ...`` is used with execution as ``main``, the scheduler won't continue until the task is completed
- If the task itself is not using ``async def ...`` but just ``def ...``, the task cannot be parallelized
- The task should release the executor every once in a while so that the scheduler can also do work
=> ENH: Add async tasks

rocketry/core/schedule.py, rocketry/session.py, rocketry/test/session/test_control.py, rocketry/test/session/test_deprecate.py
Renamed ``session.shutdown`` to ``session.shut_down`` and added ``force`` option. Force will terminate all running tasks during shutdown.
Also, if called twice, the force is set.
=> ENH: session shutdown

docs/index.rst
Fixed typo in label of url to github in docs/index.rst
=> fix typo in docs/index.rst

docs/handbooks/logging.rst
Fix typo mentioned in the issue #66
=> Fix: Typo in docs/handbooks/logging.srt

docs/code/conds/api/periodical_restricted.py, docs/handbooks/conditions/api/periodical.rst, rocketry/conditions/api.py, rocketry/test/condition/test_api.py
This PR adds ``.at(span)`` to the cond API's time-related conditions:
```python
from rocketry.conds import daily
@app.task(daily.at("11:00"))
def do_things():
...
```
Note that the above is same as ``daily.between("11:00", "12:00")`` as the definition is that ``at`` is a span of one subunit of the time period. ``weekly.at("Monday")`` is not proper English but It's the responsibility of the user to learn English.
=> ENH: Add AT to hourly, daily, weekly etc.

docs/handbooks/config.rst, requirements/build.txt, requirements/ci.txt, requirements/coverage.txt, rocketry/core/schedule.py, rocketry/core/task.py, rocketry/exc.py, rocketry/session.py, rocketry/test/condition/task/test_time.py, rocketry/test/condition/task/test_time_executable.py, rocketry/test/condition/task/test_time_runnable.py, rocketry/test/conftest.py, rocketry/test/helpers/log_helpers.py, rocketry/test/helpers/task_helpers.py, rocketry/test/schedule/test_core.py, rocketry/test/schedule/test_failure.py, rocketry/test/session/params/test_params.py, rocketry/test/session/params/test_return.py, rocketry/test/session/test_construct.py, rocketry/test/session/test_deprecate.py, rocketry/test/session/test_logs.py, rocketry/test/task/func/test_logging.py, rocketry/test/task/func/test_run.py, rocketry/test/task/func/test_run_delayed.py, rocketry/test/task/test_core.py, rocketry/test/test_testing.py, rocketry/testing/log.py
This PR has the following changes:
- add: ``silence_task_logging`` config option (log failures won't crash scheduler if true)
- More robust shut down (hooks are always run)
- Better scheduler log messages/levels
=> ENH: Option to silence log errors

rocketry/core/time/__init__.py, rocketry/core/time/base.py, rocketry/test/time/test_static.py, rocketry/time/__init__.py
This adds ``never`` timeperiod which does not have any impact on usage of the library (at the moment).
=> ENH: add never timeperiod

rocketry/core/schedule.py, rocketry/core/task.py, rocketry/test/schedule/process/test_core.py
This has two changes:
- Async and threaded tasks no longer limit max simultaneous processes
- Tasks running as ``execution="main"`` are also "alive". Useful for threaded tasks to check what's running
=> FIX: Async/threaded tasks limit max_process_count

docs/handbooks/config.rst, rocketry/session.py, rocketry/test/session/test_deprecate.py
It has caused confusion that ``process`` is the default task execution type. This PR warns if execution type is not set so that after the next release the default can be changed to ``async``.
=> REF: Change default task_execution to async

docs/versions.rst, rocketry/core/task.py, rocketry/core/time/anchor.py, rocketry/test/condition/test_api.py, rocketry/test/task/func/test_run.py, rocketry/test/time/interval/test_construct.py
Fix "at" for the end of periods.
=> BUG: timeperiod at end

rocketry/session.py, rocketry/test/app/test_app.py
Minor change in session module's remove_task() method.
=> Fix task deletion bug #130

rocketry/conditions/api.py, rocketry/conditions/task/task.py, rocketry/test/condition/test_parse.py
This pull request adds __str__ method to TaskRunnable, found in rocketry.conditions.task.task.TaskRunnable.
By adding __str__ method to TaskRunnable, we solve issue of AttributeError in issue (to be updated: I will create an issue) and let cast TaskRunnable to string.
=> add __str__ to TaskRunnable in conds

docs/cookbook/settings.rst, docs/versions.rst, rocketry/core/schedule.py, rocketry/core/task.py, rocketry/test/app/test_hooks.py, rocketry/test/session/test_logs.py, rocketry/test/task/func/test_logging.py, rocketry/test/task/test_core.py
This PR fixes the issue with incorrect cache if repo is changed with ``app.startup``.
Also, the cache init is now at session start and not at the task init.
=> BUG: Cache before startup

docs/versions.rst, rocketry/args/__init__.py, rocketry/args/builtin.py, rocketry/test/args/test_args.py
``SchedulerLogger`` is to ``TaskLogger``:
```python
from rocketry.args import TaskLogger, SchedulerLogger
@app.setup()
def setup_app(task_logger=TaskLogger(), sched_logger=SchedulerLogger()):
sched_logger.addHandler(...)
```
=> ENH: Add SchedulerLogger

rocketry/core/schedule.py, rocketry/core/task.py, rocketry/test/schedule/test_multilaunch.py
This should fix the issue with #144.
The issue was caused by that the run stack was never cleaned and the termination check included finished runs. Fixed by cleaning the run stack periodically and also now it should not terminate finished runs.
=> BUG: Fix multilaunch spam

rocketry/log/log_record.py, rocketry/pybox/time/convert.py, rocketry/test/log/test_repo.py
This PR fixes the problem with ``TaskLogRecord`` and ``TaskRunRecord``:
```
...
Traceback (most recent call last):
File "...\lib\site-packages\redbird\base.py", line 321, in data_to_item        
return self.model(**data)
File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TaskLogRecord
start
an integer is required (got type str) (type=type_error)
...
```
=> BUG: TaskLogRecord and TaskRunRecord extra fields

docs/handbooks/task/execution.rst
Just fixing a typo in the docs.
=> DOCS: fix spelling of parallelized
